Fix typo
I had a "\x" sequence in a docstring and it was causing python to raise
the following error:

ValueError: invalid \x escape

Its pretty crazy that something in a docstring could cause python to
fail to parse and execute the file.